version: '3'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    networks:
      - internal
  nginx:
    container_name: nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - 80:80
    depends_on:
      - php-fpm
    networks:
      - internal
  db:
      image: postgres
      restart: always
      networks:
        - internal
      environment:
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      volumes:
        - ./docker/postgres/datadir:/var/lib/postgresql/data
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
